# Generated by Django 5.1.4 on 2026-04-30 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('publishing', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanditArmState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alpha', models.FloatField(default=1.0)),
                ('beta', models.FloatField(default=1.0)),
                ('successes', models.IntegerField(default=0)),
                ('trials', models.IntegerField(default=0)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandit_arms', to='content.campaign')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bandit_state', to='content.postvariant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandit_arms', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-last_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField()),
                ('impressions', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='Full platform response for reference and future re-computation')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='publishing.publication')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['publication', '-captured_at'], name='analytics_m_publica_63d74a_idx'), models.Index(fields=['workspace', '-captured_at'], name='analytics_m_workspa_56b832_idx')],
            },
        ),
    ]
