# Generated by Django 5.1.4 on 2026-04-30 20:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('content', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('x', 'X / Twitter'), ('reddit', 'Reddit'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('external_id', models.CharField(help_text='User ID on the platform', max_length=120)),
                ('handle', models.CharField(blank=True, max_length=120)),
                ('display_name', models.CharField(blank=True, max_length=240)),
                ('avatar_url', models.URLField(blank=True)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reauth_required', 'Reauth required'), ('revoked', 'Revoked'), ('error', 'Error')], default='active', max_length=20)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_accounts', to='brands.brand')),
                ('connected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_accounts', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['platform', '-created_at'],
                'unique_together': {('workspace', 'platform', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, help_text="Platform's post ID", max_length=120)),
                ('external_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('deleted', 'Deleted'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='publishing.platformaccount')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='content.postvariant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-scheduled_for', '-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='publishing__workspa_d06326_idx'), models.Index(fields=['scheduled_for', 'status'], name='publishing__schedul_476d95_idx')],
            },
        ),
    ]
