# Generated by Django 5.1.4 on 2026-04-30 20:41

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('goal', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='brands.brand')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brief', models.TextField()),
                ('goals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, help_text='Short tags like: signups, brand, feedback, hire', size=None)),
                ('tone_hints', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, help_text='Short tags like: ironic, technical, formal, no_emoji', size=None)),
                ('target_platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('x', 'X / Twitter'), ('reddit', 'Reddit'), ('linkedin', 'LinkedIn')], max_length=20), default=list, size=None)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('review', 'Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('pinned_reference_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='brands.brand')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.campaign')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(help_text='x_writer, reddit_writer, linkedin_writer, critic...', max_length=80)),
                ('version', models.CharField(max_length=40)),
                ('template', models.TextField()),
                ('status', models.CharField(choices=[('experimental', 'Experimental'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='experimental', max_length=20)),
                ('eval_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.promptversion')),
                ('workspace', models.ForeignKey(blank=True, help_text='Null for global prompts, set for per-workspace fine-tuned ones', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_versions', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['agent_name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('x', 'X / Twitter'), ('reddit', 'Reddit'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('source', models.CharField(choices=[('url', 'URL'), ('paste', 'Paste'), ('winner', 'Auto-imported A/B winner')], default='url', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('raw_text', models.TextField()),
                ('media', models.JSONField(blank=True, default=list)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('source_metrics', models.JSONField(blank=True, default=dict, help_text='{likes, shares, comments, impressions, captured_at}')),
                ('extracted_features', models.JSONField(blank=True, default=dict)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('likes_count', models.IntegerField(default=0, help_text='Internal likes by team')),
                ('use_count', models.IntegerField(default=0, help_text='Times used as few-shot example')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='brands.brand')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StyleRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('platform', 'Per platform'), ('campaign', 'Per campaign')], default='global', max_length=20)),
                ('platform', models.CharField(blank=True, choices=[('x', 'X / Twitter'), ('reddit', 'Reddit'), ('linkedin', 'LinkedIn')], default='', max_length=20)),
                ('rule_text', models.CharField(max_length=400)),
                ('rationale', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paused', 'Paused')], default='proposed', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_rules', to='brands.brand')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_rules', to='content.campaign')),
                ('evidence_references', models.ManyToManyField(blank=True, related_name='supported_rules', to='content.reference')),
                ('parent_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.stylerule')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_rules', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('x', 'X / Twitter'), ('reddit', 'Reddit'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('label', models.CharField(default='A', help_text='A, B, C...', max_length=10)),
                ('content', models.TextField(blank=True)),
                ('media', models.JSONField(blank=True, default=list, help_text='[{type: image|video|gif, url, alt}]')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('is_starred', models.BooleanField(default=False, help_text='User-preferred variant')),
                ('allocation_weight', models.FloatField(default=1.0, help_text='Relative weight for bandit allocation (updated by Thompson sampling task)')),
                ('critic_notes', models.JSONField(blank=True, default=list, help_text='Array of {severity, message, fix_suggestion}')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='content.post')),
                ('generated_by_prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='content.promptversion')),
                ('inspired_by_references', models.ManyToManyField(blank=True, related_name='inspired_variants', to='content.reference')),
                ('inspired_by_style_rules', models.ManyToManyField(blank=True, related_name='inspired_variants', to='content.stylerule')),
            ],
            options={
                'ordering': ['post_id', 'platform', 'label'],
            },
        ),
        migrations.CreateModel(
            name='WinningPattern',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('x', 'X / Twitter'), ('reddit', 'Reddit'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('pattern_text', models.CharField(max_length=400)),
                ('metric', models.CharField(default='engagement_rate', help_text='engagement_rate, ctr, replies, shares...', max_length=40)),
                ('lift', models.FloatField(help_text='Relative lift vs control, e.g. 0.43 for +43%')),
                ('sample_size', models.IntegerField()),
                ('confidence_interval', models.JSONField(blank=True, default=dict)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winning_patterns', to='brands.brand')),
                ('evidence_variants', models.ManyToManyField(blank=True, related_name='evidenced_patterns', to='content.postvariant')),
                ('promoted_to_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.stylerule')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winning_patterns', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stylerule',
            name='evidence_winning_patterns',
            field=models.ManyToManyField(blank=True, related_name='supported_rules', to='content.winningpattern'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['workspace', 'status'], name='content_cam_workspa_012be4_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['workspace', 'status'], name='content_pos_workspa_bfb756_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['campaign', 'status'], name='content_pos_campaig_3c66c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promptversion',
            unique_together={('workspace', 'agent_name', 'version')},
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['workspace', 'platform'], name='content_ref_workspa_75d1d5_idx'),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='reference_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='postvariant',
            index=models.Index(fields=['post', 'platform'], name='content_pos_post_id_7dbb09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postvariant',
            unique_together={('post', 'platform', 'label')},
        ),
        migrations.AddIndex(
            model_name='winningpattern',
            index=models.Index(fields=['brand', 'platform', '-lift'], name='content_win_brand_i_00093b_idx'),
        ),
        migrations.AddIndex(
            model_name='stylerule',
            index=models.Index(fields=['brand', 'status'], name='content_sty_brand_i_ff94e7_idx'),
        ),
        migrations.AddIndex(
            model_name='stylerule',
            index=models.Index(fields=['brand', 'scope', 'platform'], name='content_sty_brand_i_43983d_idx'),
        ),
    ]
