# Generated by Django 5.1.4 on 2026-05-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvariant',
            name='hook_strategy',
            field=models.CharField(blank=True, help_text='Which hook strategy was used: curiosity, controversy, story, ...', max_length=40),
        ),
    ]
