# Generated by Django 5.1.4 on 2026-04-30 20:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('content', 'Content generation'), ('curation', 'Curator — style rules'), ('analysis', 'Analyst — insights'), ('edit', 'Inline edit (Cmd+K)'), ('brand_voice', 'Brand voice extraction')], max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('awaiting_approval', 'Awaiting human approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=30)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_tokens_in', models.IntegerField(default=0)),
                ('total_tokens_out', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('langsmith_trace_id', models.CharField(blank=True, max_length=120)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='content.post')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(help_text='Monotonic order within a run')),
                ('kind', models.CharField(choices=[('node_started', 'Node started'), ('node_finished', 'Node finished'), ('llm_call', 'LLM call'), ('tool_call', 'Tool call'), ('stream_chunk', 'Stream chunk'), ('state_update', 'State update'), ('human_input_required', 'Human input required'), ('error', 'Error'), ('info', 'Info')], max_length=30)),
                ('node_name', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agent_runs.agentrun')),
            ],
            options={
                'ordering': ['run_id', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['workspace', 'status'], name='agent_runs__workspa_8859a3_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['post', 'status'], name='agent_runs__post_id_f2c747_idx'),
        ),
        migrations.AddIndex(
            model_name='agentevent',
            index=models.Index(fields=['run', 'sequence'], name='agent_runs__run_id_1b6af5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentevent',
            unique_together={('run', 'sequence')},
        ),
    ]
