# Generated by Django 5.1.4 on 2026-05-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='kind',
            field=models.CharField(choices=[('content', 'Content generation'), ('ab_variation', 'A/B refine — variations of a winner'), ('reference_dna', 'Reference DNA extraction'), ('curation', 'Curator — style rules'), ('analysis', 'Analyst — insights'), ('edit', 'Inline edit (Cmd+K)'), ('brand_voice', 'Brand voice extraction')], max_length=30),
        ),
    ]
