# Generated by Django 5.1.4 on 2026-04-30 21:46

import apps.media.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('upload', 'User upload'), ('ai', 'AI generated'), ('url', 'Imported by URL')], default='upload', max_length=20)),
                ('file', models.FileField(blank=True, max_length=500, upload_to=apps.media.models._media_upload_path)),
                ('external_url', models.URLField(blank=True, max_length=1000)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('ai_prompt', models.TextField(blank=True, help_text='Prompt used if AI-generated')),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='brands.brand')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'source'], name='media_media_workspa_1459c7_idx')],
            },
        ),
    ]
